version: "3.1"
services:
  avanade_rpg_db:
    image: postgres:10
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: avanadeRpg
      POSTGRES_USER: avanadeRpg
      POSTGRES_DB: avanadeRpg
    ports:
      - "5433:5432"
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"

volumes:
  db-data:
    driver: local